/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
 /*\title SPI communication via QSPI
 * \abstract A QSPI module configured as SPI master sends five bytes to another QSPI module which is configured as SPI slave.
 * \description QSPI1 is configured in master mode and used to send five bytes to QSPI2 configured in slave mode.
 *              The received data is read by the CPU and compared against the transmitted data. Port pin 00.5,
 *              to which LED1 is connected, indicates the successful transfer.
 *
 * \name SPI_CPU_1_KIT_TC375_LK
 * \version V1.0.1
 * \board AURIX TC375 lite Kit, KIT_A2G_TC375_LITE, TC37xTP_A-Step
 * \keywords AURIX, Communication, Master, QSPI, SPI, SPI_CPU_1, Slave, MikroBus
 * \documents https://www.infineon.com/aurix-expert-training/Infineon-AURIX_SPI_CPU_1_KIT_TC375_LK-TR-v01_00_01-EN.pdf
 * \documents https://www.infineon.com/aurix-expert-training/TC37A_iLLD_UM_1_0_1_12_1.chm
 * \lastUpdated 2021-06-29
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "IfxStm.h"
#include "st7789_driver.h"
#include "sh1106_driver.h"
#include "fonts.h"
#include "STM_System_Time.h"
#include "Bsp.h"
#include "DHT11.h"
#include <stdarg.h>
#include <stdint.h>
#include <stdio.h>
#include "DHT11.h"
#include "Flash_Programming.h"

#define WAIT_TIME   1000        /* Number of milliseconds to wait               */

systemTime gm_time;
rawtime gm_rawtime;

#define SENSOR_DATA_FLASH_ADDRESS 0xA00E0000  // Address in PFLASH to store sensor data

#pragma section farrom "Sensor_Data_section"
const SensorData Default_Sensor_Data = {
    .marker = SENSOR_DATA_MARKER,
    .maxHumidity = DEFAULT_MAX_HUMIDITY,
    .minHumidity = DEFAULT_MIN_HUMIDITY,
    .maxHumidityTime = {DEFAULT_TIME_HOUR, DEFAULT_TIME_MINUTE, DEFAULT_TIME_SECOND, 0, DEFAULT_DATE_DAY, DEFAULT_DATE_MONTH, DEFAULT_DATE_YEAR, 0, 0},
    .minHumidityTime = {DEFAULT_TIME_HOUR, DEFAULT_TIME_MINUTE, DEFAULT_TIME_SECOND, 0, DEFAULT_DATE_DAY, DEFAULT_DATE_MONTH, DEFAULT_DATE_YEAR, 0, 0},
    .maxTemperature = DEFAULT_MAX_TEMPERATURE,
    .minTemperature = DEFAULT_MIN_TEMPERATURE,
    .maxTemperatureTime = {DEFAULT_TIME_HOUR, DEFAULT_TIME_MINUTE, DEFAULT_TIME_SECOND, 0, DEFAULT_DATE_DAY, DEFAULT_DATE_MONTH, DEFAULT_DATE_YEAR, 0, 0},
    .minTemperatureTime = {DEFAULT_TIME_HOUR, DEFAULT_TIME_MINUTE, DEFAULT_TIME_SECOND, 0, DEFAULT_DATE_DAY, DEFAULT_DATE_MONTH, DEFAULT_DATE_YEAR, 0, 0}
};
#pragma section farrom restore

IFX_ALIGN(4) IfxCpu_syncEvent g_cpuSyncEvent = 0;

/* DHT11 sensor data update time: 5 s */
#define DHT11_UPDATE_TIME                   500000000

uint32 _lastreadtime, _maxcycles;
uint8 pullTime; // Time (in usec) to pull up data line before reading

// Data structures
typedef struct {
    float value;
    float max;
    float min;
    systemTime maxTime;
    systemTime minTime;
} SensorReading;

// Global variables
static SensorReading g_humidity = {0.0f, -100.0f, 100.0f};
static SensorReading g_temperature = {0.0f, -100.0f, 100.0f};
static Ifx_TickTime g_ticksFor1s;

// Define the interval for storing data (15 minutes in milliseconds)
#define STORE_INTERVAL_MS (1 * 60 * 1000)

static SensorData g_sensorData;
static uint32_t lastStoreTime = 0;

// Add safe timer conversion function
static uint32_t getStmTicks(void) {
    uint64_t ticks = IfxStm_get(&MODULE_STM0);
    // Handle potential overflow, keep lower 32 bits
    return (uint32_t)(ticks & 0xFFFFFFFF);
}

// Update function prototype to use uint32_t
void delay_ms(uint32_t ms);

// Update function implementation
void delay_ms(uint32_t ms) {
    uint32_t ticksFor1ms = IfxStm_getTicksFromMilliseconds(&MODULE_STM0, 1);
    uint32_t startTime = getStmTicks();
    while ((getStmTicks() - startTime) < (ticksFor1ms * ms)) {}
}

// Format time string as "HH:MM:SS"
static void mySprint(char *buffer, uint8_t hours, uint8_t minutes, uint8_t seconds)
{
    // Format hours
    if (hours < 10) {
        *buffer++ = '0';
        *buffer++ = '0' + hours;
    } else {
        *buffer++ = '0' + (hours / 10);
        *buffer++ = '0' + (hours % 10);
    }
    
    // Add colon
    *buffer++ = ':';
    
    // Format minutes
    if (minutes < 10) {
        *buffer++ = '0';
        *buffer++ = '0' + minutes;
    } else {
        *buffer++ = '0' + (minutes / 10);
        *buffer++ = '0' + (minutes % 10);
    }
    
    // Add colon
    *buffer++ = ':';
    
    // Format seconds
    if (seconds < 10) {
        *buffer++ = '0';
        *buffer++ = '0' + seconds;
    } else {
        *buffer++ = '0' + (seconds / 10);
        *buffer++ = '0' + (seconds % 10);
    }
    
    // Add null terminator
    *buffer = '\0';
}

// Function prototype
static void mySprintMs(char *buffer, uint8_t hours, uint8_t minutes, 
                      uint8_t seconds);

// Implementation
static void mySprintMs(char *buffer, uint8_t hours, uint8_t minutes, 
                      uint8_t seconds) 
{
    // Format hours
    if (hours < 10) {
        *buffer++ = '0';
        *buffer++ = '0' + hours;
    } else {
        *buffer++ = '0' + (hours / 10);
        *buffer++ = '0' + (hours % 10);
    }
    
    // Add colon
    *buffer++ = ':';
    
    // Format minutes
    if (minutes < 10) {
        *buffer++ = '0';
        *buffer++ = '0' + minutes;
    } else {
        *buffer++ = '0' + (minutes / 10);
        *buffer++ = '0' + (minutes % 10);
    }
    
    // Add colon
    *buffer++ = ':';
    
    // Format seconds
    if (seconds < 10) {
        *buffer++ = '0';
        *buffer++ = '0' + seconds;
    } else {
        *buffer++ = '0' + (seconds / 10);
        *buffer++ = '0' + (seconds % 10);
    }
        
    // Add null terminator
    *buffer = '\0';
}

void createBox(void)
{
 /*  --------------------------------------
    |         Create a Box/Table          |  
    --------------------------------------
    |                                     |
    --------------------------------------
*/
        ST7789_DrawVLine(1, 25, 240, ST7789_GRAY);
        ST7789_DrawVLine(120, 25, 25, ST7789_GRAY);
        ST7789_DrawVLine(180, 40, 60, ST7789_GRAY);
        ST7789_DrawVLine(120, 100, 110, ST7789_GRAY);
        ST7789_DrawVLine(70, 210, 30, ST7789_GRAY);
        ST7789_DrawVLine(319, 25, 240, ST7789_GRAY);
        ST7789_DrawHLine(1, 25, 319, ST7789_GRAY);
        ST7789_DrawHLine(1, 50, 319, ST7789_GRAY);
        ST7789_DrawHLine(1, 75, 319, ST7789_GRAY);
        ST7789_DrawHLine(1, 100, 319, ST7789_GRAY);
        ST7789_DrawHLine(1, 150, 319, ST7789_GRAY);
        ST7789_DrawHLine(1, 210, 319, ST7789_GRAY);
        ST7789_DrawHLine(1, 239, 319, ST7789_GRAY);
}

// Function prototypes
extern void processDHT22Data(void);
static void initSystem(void);
static void updateSensor(SensorReading* reading, float newValue);
static void displayReadings(void);
static void mySprint(char *buffer, uint8_t hours, uint8_t minutes, uint8_t seconds);
static void mySprintMs(char *buffer, uint8_t hours, uint8_t minutes, 
                      uint8_t seconds);
static void storeSensorData(void);

// Main function
void core0_main(void) {
    initSystem();
    uint32_t lastTickTime = getStmTicks();
    uint32_t targetInterval = g_ticksFor1s; // 1 second in ticks
    
    while(1) {
        uint32_t currentTicks = getStmTicks();
        uint32_t elapsedTicks = currentTicks - lastTickTime;
        
        // Calculate wait time compensating for processing delay
        uint32_t adjustedWait = (elapsedTicks < targetInterval) ? 
                               (targetInterval - elapsedTicks) : 0;
        
        // Get time readings first
        gm_time = getTime();
        gm_rawtime = getRawTime();
        
        // Process sensors and update display
        processDHT22Data();
        extern float humidity, temperature;
        updateSensor(&g_humidity, humidity);
        updateSensor(&g_temperature, temperature);
        displayReadings();
        
        // Store sensor data every 15 minutes
        if ((currentTicks - lastStoreTime) >= IfxStm_getTicksFromMilliseconds(&MODULE_STM0, STORE_INTERVAL_MS)) {
            //storeSensorData();
            lastStoreTime = currentTicks;
        }
        
        // Calculate elapsed time after processing
        currentTicks = getStmTicks();
        elapsedTicks = currentTicks - lastTickTime;
        
        // Calculate wait time compensating for processing delay
        adjustedWait = (elapsedTicks < targetInterval) ? 
                      (targetInterval - elapsedTicks) : 0;
        
        // Wait remaining time to maintain precise 1-second interval
        if (adjustedWait > 0) {
            waitTime(adjustedWait);
        }
        
        // Update last tick time for next iteration
        lastTickTime = getStmTicks();
    }
}

static void initSystem(void) {
    IfxCpu_enableInterrupts();
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
    
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);
    
    g_ticksFor1s = IfxStm_getTicksFromMilliseconds(BSP_DEFAULT_TIMER, WAIT_TIME);
    
    ST7789_Init();
    ST7789_FillScreen(ST7789_BLACK);
    createBox();
    
    ST7789_Print(20, 10, "- Aurix TC375TP Test Program -", ST7789_WHITE, ST7789_BLACK, 1);
    ST7789_Print(10, 30, "Core0 run", ST7789_BLUE, ST7789_BLACK, 2);

    // Read sensor data from flash
    readSensorDataFromFlash(&g_sensorData);

    // Initialize global variables with sensor data
    g_humidity.max = g_sensorData.maxHumidity;
    g_humidity.min = g_sensorData.minHumidity;
    g_humidity.maxTime = g_sensorData.maxHumidityTime;
    g_humidity.minTime = g_sensorData.minHumidityTime;

    g_temperature.max = g_sensorData.maxTemperature;
    g_temperature.min = g_sensorData.minTemperature;
    g_temperature.maxTime = g_sensorData.maxTemperatureTime;
    g_temperature.minTime = g_sensorData.minTemperatureTime;
}

static void updateSensor(SensorReading* reading, float newValue) {
    reading->value = newValue;
    
    if (newValue > reading->max) {
        reading->max = newValue;
        reading->maxTime = gm_time;
    }
    if (newValue < reading->min) {
        reading->min = newValue;
        reading->minTime = gm_time;
    }
}

static void storeSensorData(void) {
    g_sensorData.maxHumidity = g_humidity.max;
    g_sensorData.minHumidity = g_humidity.min;
    g_sensorData.maxHumidityTime = g_humidity.maxTime;
    g_sensorData.minHumidityTime = g_humidity.minTime;
    g_sensorData.maxTemperature = g_temperature.max;
    g_sensorData.minTemperature = g_temperature.min;
    g_sensorData.maxTemperatureTime = g_temperature.maxTime;
    g_sensorData.minTemperatureTime = g_temperature.minTime;

    writeSensorDataToFlash(&g_sensorData);
}

// Update display function to use mySprintMs
static void displayReadings(void) {
    char buffer[32];
    char timeStr[9];  // Increased size for milliseconds format
    char timeRaw[9];  // Increased size for milliseconds format
    
    gm_rawtime = getRawTime();  // Call the function which gets the system time
    
    // Display current time with milliseconds
    mySprintMs(timeRaw, 
          (uint8_t)gm_rawtime.hours,
          (uint8_t)gm_rawtime.minutes,
          (uint8_t)gm_rawtime.seconds);
    ST7789_Print(165, 30, timeRaw, ST7789_BLUE, ST7789_BLACK, 2);
    
    // Display current values
    snprintf(buffer, sizeof(buffer), "%.1f%%", g_humidity.value);
    ST7789_Print(10, 55, "Humidity", ST7789_GREEN, ST7789_BLACK, 2);
    ST7789_Print(190, 55, buffer, ST7789_GREEN, ST7789_BLACK, 2);
    
    snprintf(buffer, sizeof(buffer), "%.1fC", g_temperature.value);
    ST7789_Print(10, 80, "Temp", ST7789_GREEN, ST7789_BLACK, 2);
    ST7789_Print(190, 80, buffer, ST7789_GREEN, ST7789_BLACK, 2);
    
    // Display max/min values
    mySprint(timeStr, 
             (uint8_t)g_humidity.maxTime.hours,
             (uint8_t)g_humidity.maxTime.minutes, 
             (uint8_t)g_humidity.maxTime.seconds);
    snprintf(buffer, sizeof(buffer), "%.1f%% %s", g_humidity.max, timeStr);
    ST7789_Print(10, 105, "Max Hum:", ST7789_DARK_RED, ST7789_BLACK, 2);
    ST7789_Print(125, 105, buffer, ST7789_DARK_RED, ST7789_BLACK, 2);
    
    mySprint(timeStr, 
             (uint8_t)g_humidity.minTime.hours,    // Explicit cast
             (uint8_t)g_humidity.minTime.minutes,  // Explicit cast
             (uint8_t)g_humidity.minTime.seconds); // Explicit cast
    snprintf(buffer, sizeof(buffer), "%.1f%% %s", g_humidity.min, timeStr);
    ST7789_Print(10, 130, "Min Hum:", ST7789_GRAY, ST7789_BLACK, 2);
    ST7789_Print(125, 130, buffer, ST7789_GRAY, ST7789_BLACK, 2);
    
    mySprint(timeStr, 
             (uint8_t)g_temperature.maxTime.hours,    // Explicit cast
             (uint8_t)g_temperature.maxTime.minutes,  // Explicit cast
             (uint8_t)g_temperature.maxTime.seconds); // Explicit cast
    snprintf(buffer, sizeof(buffer), "%.1fC %s", g_temperature.max, timeStr);
    ST7789_Print(10, 160, "Max Temp:", ST7789_DARK_RED, ST7789_BLACK, 2);
    ST7789_Print(125, 160, buffer, ST7789_DARK_RED, ST7789_BLACK, 2);
    
    mySprint(timeStr, 
             (uint8_t)g_temperature.minTime.hours,
             (uint8_t)g_temperature.minTime.minutes, 
             (uint8_t)g_temperature.minTime.seconds);
    snprintf(buffer, sizeof(buffer), "%.1fC %s", g_temperature.min, timeStr);
    ST7789_Print(10, 185, "Min Temp:", ST7789_GRAY, ST7789_BLACK, 2);
    ST7789_Print(125, 185, buffer, ST7789_GRAY, ST7789_BLACK, 2);

    // Display date
    snprintf(buffer, sizeof(buffer), "%02d:%02d:%02d %02d.%02d.%04d", \
    (uint8_t)gm_time.hours,    // Explicit cast
    (uint8_t)gm_time.minutes,  // Explicit cast
    (uint8_t)gm_time.seconds,  // Explicit cast
    (uint8_t)gm_time.day,      // Explicit cast
    (uint8_t)gm_time.month,    // Explicit cast
    (uint16_t)gm_time.year);   // Use uint16_t for year
    ST7789_Print(15, 220, "Date", ST7789_BROWN, ST7789_BLACK, 2);
    ST7789_Print(75, 220, buffer, ST7789_BROWN, ST7789_BLACK, 2);
}
