/**********************************************************************************************************************
 * \file Flash_Programming.h
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

#ifndef FLASH_PROGRAMMING_H_
#define FLASH_PROGRAMMING_H_

#include "STM_System_Time.h"
#include "IfxDmu_reg.h"

#define SENSOR_DATA_MARKER 0xDEADBEEF
#define SENSOR_DATA_FLASH_ADDRESS 0xA00E0000  // Address in PFLASH to store sensor data
#define DEFAULT_MAX_HUMIDITY 56.9f
#define DEFAULT_MIN_HUMIDITY 49.8f
#define DEFAULT_MAX_TEMPERATURE 20.9f
#define DEFAULT_MIN_TEMPERATURE 18.9f

#define DEFAULT_DATE_YEAR 2011
#define DEFAULT_DATE_MONTH 12
#define DEFAULT_DATE_DAY 01
#define DEFAULT_TIME_HOUR 12
#define DEFAULT_TIME_MINUTE 15
#define DEFAULT_TIME_SECOND 00

typedef struct {
    uint32_t marker;
    float maxHumidity;
    float minHumidity;
    systemTime maxHumidityTime;
    systemTime minHumidityTime;
    float maxTemperature;
    float minTemperature;
    systemTime maxTemperatureTime;
    systemTime minTemperatureTime;
} SensorData;

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/
void initLEDs(void);            /* Function that initializes the LEDs                                               */
void writeSensorDataToFlash(const SensorData* data);
void readSensorDataFromFlash(SensorData* data);

#endif /* FLASH_PROGRAMMING_H_ */
