/**********************************************************************************************************************
 * \file st7789_driver.h
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

// st7789_driver.h
#ifndef ST7789_DRIVER_H
#define ST7789_DRIVER_H

#include "Ifx_Types.h"
#include "IfxQspi_SpiMaster.h"
#include "IfxQspi_SpiSlave.h"
#include "IfxPort.h"
#include <stdint.h>

// Display dimensions
#define ST7789_WIDTH    240
#define ST7789_HEIGHT   320

// Color definitions
#define ST7789_BLACK    0x0000
#define ST7789_WHITE    0xFFFF
#define ST7789_RED      0xF800
#define ST7789_GREEN    0x07E0
#define ST7789_BLUE     0x001F
#define ST7789_YELLOW   0xFFE0
#define ST7789_MAGENTA  0xF81F
#define ST7789_CYAN     0x07FF

// Additional Color Definitions
#define ST7789_ORANGE     0xFD20  // Orange
#define ST7789_PURPLE     0x801F  // Purple
#define ST7789_BROWN      0xB240  // Brown
#define ST7789_GRAY       0x8410  // Gray
#define ST7789_LIGHT_GREEN 0x87F0 // Light Green
#define ST7789_LIGHT_BLUE  0x7FFF // Light Blue
#define ST7789_DARK_GREEN  0x0400 // Dark Green
#define ST7789_LIGHT_GRAY  0xC618 // Light Gray
#define ST7789_DARK_RED    0x8000 // Dark Red
#define ST7789_NAVY        0x000F // Navy
#define ST7789_SKY_BLUE    0x867F // Sky Blue
#define ST7789_PINK        0xF81F // Pink
#define ST7789_GOLD        0xFEA0 // Gold
#define ST7789_SILVER      0xC618 // Silver
#define ST7789_VIOLET      0x901A // Violet
#define ST7789_INDIGO      0x4810 // Indigo

#define DATA_TO_TRANSFER     5                       /* Buffers size                  */

// Function prototypes
void ST7789_Init(void);
void ST7789_DrawPixel(uint16_t x, uint16_t y, uint16_t color);
void ST7789_FillRect(uint16_t x, uint16_t y, uint16_t w, uint16_t h, uint16_t color);
void ST7789_FillScreen(uint16_t color);
void ST7789_Clear(void);
void ST7789_DrawHLine(uint16_t x, uint16_t y, uint16_t w, uint16_t color);
void ST7789_DrawVLine(uint16_t x, uint16_t y, uint16_t h, uint16_t color);
void ST7789_SetRotation(uint8_t rotation);
void ST7789_Print(uint16_t x, uint16_t y, const char *text, uint16_t color, uint16_t bg, uint8_t size);


typedef struct
{
    uint8_t spiMasterTxBuffer[DATA_TO_TRANSFER];       /* QSPI Master Transmit buffer   */
    uint8_t spiMasterRxBuffer[DATA_TO_TRANSFER];       /* QSPI Master Receive buffer    */
    uint8_t spiSlaveTxBuffer[DATA_TO_TRANSFER];        /* QSPI Slave Transmit buffer    */
    uint8_t spiSlaveRxBuffer[DATA_TO_TRANSFER];        /* QSPI Slave Receive buffer     */
} qspiBuffers;

typedef struct
{
    qspiBuffers               spiBuffers;           /* Buffers instance              */
    IfxQspi_SpiMaster         spiMaster;            /* QSPI Master handle            */
    IfxQspi_SpiMaster_Channel spiMasterChannel;     /* QSPI Master Channel handle    */
    IfxQspi_SpiSlave          spiSlave;             /* QSPI Slave handle             */
} qspiComm;


#endif // ST7789_DRIVER_H
