/**********************************************************************************************************************
 * \file st7789_driver.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


// st7789_driver.c
#include "st7789_driver.h"

#include "IfxScuRcu.h"
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxStm.h"
#include "IfxPort.h"
#include "IfxCpu_Irq.h"
#include "font5x7.h"
#include "fonts.h"
#include <Qspi/SpiMaster/IfxQspi_SpiMaster.h>


// mikroBUS socket pin definitions for TC375_LK
// #define TFT_BLK     &MODULE_P10,4   // GPIO for Backlight
// #define TFT_RST     &MODULE_P10,6   // GPIO for Reset
// #define TFT_CS      &MODULE_P14,7   // SLSO (CS) for QSPI2
// #define TFT_DC      &MODULE_P15,4   // GPIO for Data/Command
// #define TFT_MOSI    &MODULE_P15,6   // MTSR (Master Out)
// #define TFT_MISO    &MODULE_P15,7   // MRST (Master In, optional)
// #define TFT_SCK     &MODULE_P15,8   // SCLK

#define TFT_BLK     &MODULE_P10,4   // GPIO for Backlight
#define TFT_RST     &MODULE_P10,6   // GPIO for Reset
#define TFT_CS      &MODULE_P10,5   // SLSO (CS) for QSPI1
#define TFT_DC      &MODULE_P15,4   // GPIO for Data/Command
#define TFT_MOSI    &MODULE_P10,3   // MTSR (MOSI)
#define TFT_MISO    &MODULE_P10,1   // MRST (Master In, optional)
#define TFT_SCK     &MODULE_P10,2   // SCLK

// ST7789 Commands
#define ST7789_NOP      0x00
#define ST7789_SWRESET  0x01
#define ST7789_SLPIN    0x10
#define ST7789_SLPOUT   0x11
#define ST7789_NORON    0x13
#define ST7789_INVOFF   0x20
#define ST7789_INVON    0x21
#define ST7789_DISPOFF  0x28
#define ST7789_DISPON   0x29
#define ST7789_CASET    0x2A
#define ST7789_RASET    0x2B
#define ST7789_RAMWR    0x2C
#define ST7789_MADCTL   0x36
#define ST7789_COLMOD   0x3A

/* Interrupt Service Routine priorities for Master and Slave SPI communication */
#define ISR_PRIORITY_MASTER_TX      50
#define ISR_PRIORITY_MASTER_RX      51
#define ISR_PRIORITY_MASTER_ER      52
#define ISR_PRIORITY_SLAVE_TX       53
#define ISR_PRIORITY_SLAVE_RX       54
#define ISR_PRIORITY_SLAVE_ER       55

#define MASTER_CHANNEL_BAUDRATE     27000000         /* Master channel baud rate                                     */

// QSPI configuration structures
// static IfxQspi_SpiMaster spi;
qspiComm g_qspi;
//static IfxQspi_SpiMaster_Channel spiChannel;

#define SPI_BUFFER_SIZE 8
uint8_t   spiTxBuffer[SPI_BUFFER_SIZE];
uint8_t   spiRxBuffer[SPI_BUFFER_SIZE];

// Display orientation
static uint8_t rotation = 1;
static int16_t _width = ST7789_WIDTH;
static int16_t _height = ST7789_HEIGHT;

/*********************************************************************************************************************/
/*----------------------------------------------Function Implementations---------------------------------------------*/
/*********************************************************************************************************************/
IFX_INTERRUPT(masterTxISR, 0, ISR_PRIORITY_MASTER_TX);                  /* SPI Master ISR for transmit data         */
IFX_INTERRUPT(masterRxISR, 0, ISR_PRIORITY_MASTER_RX);                  /* SPI Master ISR for receive data          */
IFX_INTERRUPT(masterErISR, 0, ISR_PRIORITY_MASTER_ER);                  /* SPI Master ISR for error                 */

void masterTxISR()
{
    IfxCpu_enableInterrupts();
    IfxQspi_SpiMaster_isrTransmit(&g_qspi.spiMaster);
}

void masterRxISR()
{
    IfxCpu_enableInterrupts();
    IfxQspi_SpiMaster_isrReceive(&g_qspi.spiMaster);
}

void masterErISR()
{
    IfxCpu_enableInterrupts();
    IfxQspi_SpiMaster_isrError(&g_qspi.spiMaster);
}


// Utility function for delays
static void delay_ms(uint32_t ms) {
    uint32_t ticksFor1ms = IfxStm_getTicksFromMilliseconds(&MODULE_STM0, 1);
    uint32_t startTime = IfxStm_get(&MODULE_STM0);
    
    while ((uint32_t)(IfxStm_get(&MODULE_STM0) - startTime) < (ticksFor1ms * ms)) {
        // Wait
    }
}

// Initialize GPIO pins
static void ST7789_InitGPIO(void) {
    IfxPort_setPinModeOutput(TFT_BLK, IfxPort_OutputMode_pushPull, IfxPort_OutputIdx_general);
    IfxPort_setPinHigh(TFT_BLK);

    // Initialize Data/Command pin
    IfxPort_setPinModeOutput(TFT_DC, IfxPort_OutputMode_pushPull, IfxPort_OutputIdx_general);
    IfxPort_setPinHigh(TFT_DC);

    // Initialize Chip Select pin
    IfxPort_setPinModeOutput(TFT_CS, IfxPort_OutputMode_pushPull, IfxPort_OutputIdx_general);
    IfxPort_setPinHigh(TFT_CS);

    // Initialize Reset pin
    IfxPort_setPinModeOutput(TFT_RST, IfxPort_OutputMode_pushPull, IfxPort_OutputIdx_general);
    IfxPort_setPinHigh(TFT_RST);

    // Initialize Clock pin
    IfxPort_setPinModeOutput(TFT_SCK, IfxPort_OutputMode_pushPull, IfxPort_OutputIdx_general);
    IfxPort_setPinHigh(TFT_SCK);

    // Initialize MOSI pin
    IfxPort_setPinModeOutput(TFT_MOSI, IfxPort_OutputMode_pushPull, IfxPort_OutputIdx_general);
    IfxPort_setPinHigh(TFT_MOSI);

    // Initialize MISO pin (optional)
    IfxPort_setPinModeInput(TFT_MISO, IfxPort_InputMode_pullUp);


}

// Initialize QSPI for communication
static void ST7789_InitQSPI(void) {
    IfxQspi_SpiMaster_Config spiMasterConfig;

    IfxQspi_SpiMaster_initModuleConfig(&spiMasterConfig, &MODULE_QSPI1);

    spiMasterConfig.base.mode = SpiIf_Mode_master;

    // Configure QSPI pins
    const IfxQspi_SpiMaster_Pins qspi1MasterPins = {
        &IfxQspi1_SCLK_P10_2_OUT, IfxPort_OutputMode_pushPull,          /* SCLK Pin                       (CLK)     */
        &IfxQspi1_MTSR_P10_3_OUT, IfxPort_OutputMode_pushPull,          /* MasterTransmitSlaveReceive pin (MOSI)    */
        &IfxQspi1_MRSTA_P10_1_IN, IfxPort_InputMode_pullDown,           /* MasterReceiveSlaveTransmit pin (MISO)    */
        IfxPort_PadDriver_cmosAutomotiveSpeed3                          /* Pad driver mode                          */
    };
    spiMasterConfig.pins = &qspi1MasterPins;  
    
    /* Set the ISR priorities and the service provider */
    spiMasterConfig.base.txPriority = ISR_PRIORITY_MASTER_TX;
    spiMasterConfig.base.rxPriority = ISR_PRIORITY_MASTER_RX;
    spiMasterConfig.base.erPriority = ISR_PRIORITY_MASTER_ER;
    spiMasterConfig.base.isrProvider = IfxSrc_Tos_cpu0;
    
/* Initialize the QSPI Master module */
    IfxQspi_SpiMaster_initModule(&g_qspi.spiMaster, &spiMasterConfig);
  
}

void initQSPI1MasterChannel(void)
{
    IfxQspi_SpiMaster_ChannelConfig spiMasterChannelConfig;             /* Define a Master Channel configuration    */

    /* Initialize the configuration with default values */
    IfxQspi_SpiMaster_initChannelConfig(&spiMasterChannelConfig, &g_qspi.spiMaster);

    spiMasterChannelConfig.base.baudrate = MASTER_CHANNEL_BAUDRATE;     /* Set SCLK frequency to 1 MHz              */
    spiMasterChannelConfig.base.mode.clockPolarity = 1;
    

    /* Select the port pin for the Chip Select signal */
    const IfxQspi_SpiMaster_Output qspi1SlaveSelect = {                 /* QSPI1 Master selects the QSPI1 Slave     */
        &IfxQspi1_SLSO9_P10_5_OUT, IfxPort_OutputMode_pushPull,         /* Slave Select port pin (CS)               */
        IfxPort_PadDriver_cmosAutomotiveSpeed1                          /* Pad driver mode                          */
    };
    spiMasterChannelConfig.sls.output = qspi1SlaveSelect;

    /* Initialize the QSPI Master channel */
    IfxQspi_SpiMaster_initChannel(&g_qspi.spiMasterChannel, &spiMasterChannelConfig);
}

/* QSPI Master SW buffer initialization
 * This function initializes SW buffers the Master uses.
 */
void initQSPI1MasterBuffers(void)
{
    for (uint8 i = 0; i < DATA_TO_TRANSFER; i++)
    {
        g_qspi.spiBuffers.spiMasterTxBuffer[i] = (uint8)(i + 1);        /* Fill TX Master Buffer with pattern       */
        g_qspi.spiBuffers.spiMasterRxBuffer[i] = 0;                     /* Clear RX Buffer                          */
    }
}

// Send command to display
static void ST7789_WriteCommand(uint8_t cmd) {
    IfxPort_setPinLow(TFT_DC);  // Command mode
    IfxPort_setPinLow(TFT_CS);  // Select display

    while(IfxQspi_SpiMaster_getStatus(&g_qspi.spiMasterChannel) == SpiIf_Status_busy) {
        // Wait until the previous communication has finished, if any
    }

    IfxQspi_SpiMaster_exchange(&g_qspi.spiMasterChannel, &cmd, NULL, 1);

    IfxPort_setPinHigh(TFT_CS);  // Deselect display
}

// Send data to display
static void ST7789_WriteData(uint8_t data) {
    IfxPort_setPinHigh(TFT_DC);  // Data mode
    IfxPort_setPinLow(TFT_CS);   // Select display

    while(IfxQspi_SpiMaster_getStatus(&g_qspi.spiMasterChannel) == SpiIf_Status_busy) {
        // Wait until the previous communication has finished, if any
    }

    IfxQspi_SpiMaster_exchange(&g_qspi.spiMasterChannel, &data, NULL, 1);

    IfxPort_setPinHigh(TFT_CS);  // Deselect display
}

// Initialize display
void ST7789_Init(void) {
    // Initialize GPIO and QSPI
    ST7789_InitGPIO();
    ST7789_InitQSPI();
    /* Secondly initialize the Master */
    //initQSPI1Master();
    initQSPI1MasterChannel();
    initQSPI1MasterBuffers();    

    // Hardware reset
    IfxPort_setPinLow(TFT_RST);
    delay_ms(100);
    IfxPort_setPinHigh(TFT_RST);
    delay_ms(100);

    // Software reset
    ST7789_WriteCommand(ST7789_SWRESET);
    delay_ms(150);

    // Exit sleep mode
    ST7789_WriteCommand(ST7789_SLPOUT);
    delay_ms(120);

    // Set color mode to 16-bit per pixel
    ST7789_WriteCommand(ST7789_COLMOD);
    ST7789_WriteData(0x55);

    // Set display rotation
    ST7789_SetRotation(rotation);

    // Enable inversion
    ST7789_WriteCommand(ST7789_INVOFF);

    // Turn on display
    ST7789_WriteCommand(ST7789_NORON);
    delay_ms(50);
    ST7789_WriteCommand(ST7789_DISPON);
    delay_ms(100);
}

// Set drawing window
static void ST7789_SetWindow(uint16_t x0, uint16_t y0, uint16_t x1, uint16_t y1) {
    ST7789_WriteCommand(ST7789_CASET);
    ST7789_WriteData(x0 >> 8);
    ST7789_WriteData(x0 & 0xFF);
    ST7789_WriteData(x1 >> 8);
    ST7789_WriteData(x1 & 0xFF);

    ST7789_WriteCommand(ST7789_RASET);
    ST7789_WriteData(y0 >> 8);
    ST7789_WriteData(y0 & 0xFF);
    ST7789_WriteData(y1 >> 8);
    ST7789_WriteData(y1 & 0xFF);

    ST7789_WriteCommand(ST7789_RAMWR);
}

// Draw single pixel
void ST7789_DrawPixel(uint16_t x, uint16_t y, uint16_t color) {
    if((x >= _width) || (y >= _height)) return;

    ST7789_SetWindow(x, y, x, y);

    ST7789_WriteData(color >> 8);
    ST7789_WriteData(color & 0xFF);
}

// Fill rectangle
void ST7789_FillRect(uint16_t x, uint16_t y, uint16_t w, uint16_t h, uint16_t color) {
    if((x >= _width) || (y >= _height)) return;

    if((x + w - 1) >= _width)  w = _width  - x;
    if((y + h - 1) >= _height) h = _height - y;

    ST7789_SetWindow(x, y, x+w-1, y+h-1);

    for(uint32_t i = 0; i < w*h; i++) {
        ST7789_WriteData(color >> 8);
        ST7789_WriteData(color & 0xFF);
    }
}

void ST7789_DrawChar(uint16_t x, uint16_t y, char c, uint16_t color, uint16_t bg, uint8_t size) {
    if ((x >= _width) || (y >= _height) || ((x + 5 * size - 1) >= _width) || ((y + 7 * size - 1) >= _height))
        return;

    for (int8_t i = 0; i < 5; i++) {
        uint8_t line = font5x7[c - 32][i];
        for (int8_t j = 0; j < 8; j++, line >>= 1) {
            if (line & 1) {
                if (size == 1)
                    ST7789_DrawPixel(x + i, y + j, color);
                else
                    ST7789_FillRect(x + i * size, y + j * size, size, size, color);
            } else if (bg != color) {
                if (size == 1)
                    ST7789_DrawPixel(x + i, y + j, bg);
                else
                    ST7789_FillRect(x + i * size, y + j * size, size, size, bg);
            }
        }
    }
}

void ST7789_Print(uint16_t x, uint16_t y, const char *text, uint16_t color, uint16_t bg, uint8_t size) {
    while (*text) {
        if (*text == '\n') {
            y += size * 8;
            x = 0;
        } else if (*text == '\r') {
            // Skip carriage return
        } else {
            ST7789_DrawChar(x, y, *text, color, bg, size);
            x += size * 6;
            if (x + 5 * size >= _width) {
                x = 0;
                y += size * 8;
            }
        }
        text++;
    }
}

// Fill entire screen
void ST7789_FillScreen(uint16_t color) {
    ST7789_FillRect(0, 0, _width, _height, color);
}

void ST7789_Clear(void) {
    ST7789_FillScreen(ST7789_BLACK);
}

// Draw horizontal line
void ST7789_DrawHLine(uint16_t x, uint16_t y, uint16_t w, uint16_t color) {
    ST7789_FillRect(x, y, w, 1, color);
}

// Draw vertical line
void ST7789_DrawVLine(uint16_t x, uint16_t y, uint16_t h, uint16_t color) {
    ST7789_FillRect(x, y, 1, h, color);
}

// Set display rotation
void ST7789_SetRotation(uint8_t m) {
    ST7789_WriteCommand(ST7789_MADCTL);

    switch (m) {
        case 0:  // Portrait
            ST7789_WriteData(0x00);
            _width = ST7789_WIDTH;
            _height = ST7789_HEIGHT;
            break;
        case 1:  // Landscape
            ST7789_WriteData(0x60);
            _width = ST7789_HEIGHT;
            _height = ST7789_WIDTH;
            break;
        case 2:  // Portrait inverted
            ST7789_WriteData(0xC0);
            _width = ST7789_WIDTH;
            _height = ST7789_HEIGHT;
            break;
        case 3:  // Landscape inverted
            ST7789_WriteData(0xA0);
            _width = ST7789_HEIGHT;
            _height = ST7789_WIDTH;
            break;
    }

    rotation = m;
}
