/**********************************************************************************************************************
 * \file STM_System_Time.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "STM_System_Time.h"
#include "IfxStm.h"
#include <time.h>
#include <stdio.h>
#include <stdint.h>
#include <string.h>

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define DAY_IN_SECONDS      86400   /* Define the number of seconds in one day      */
#define HOURS_IN_SECONDS    3600    /* Define the number of seconds in one hour     */
#define MIN_IN_SECONDS      60      /* Define the number of seconds in one minute   */
#define HOURS_PER_DAY       24
#define MINUTES_PER_HOUR    60
#define SECONDS_PER_MINUTE  60

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
systemTime g_time;                 /* Instance of the structure time to store the system time  */
rawtime g_rawtime;                /* Instance of the structure rawtime to store the system time  */
static boolean timeInitialized = FALSE;
static uint32_t baseSeconds = 0;

// Remove test mode variables
// static boolean testMode = FALSE;
// static uint32_t testModeSpeed = 1000;
// static uint64_t lastTestTicks = 0;

// Add timing control variables
//static uint64_t lastProcessingTime = 0;
static uint64_t processingOverhead = 0;

// Store base date in days
static uint32_t baseDateDays = 0U;

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
/* This function gets the system time and converts it in days hours minutes and seconds */

// Helper function: Convert a date to total days since a reference year (e.g., 1970)
static uint32_t dateToDays(uint16_t year, uint8_t month, uint8_t day)
{
    // Simple approach ignoring leap years for brevity:
    // (Year − 1970) × 365 + sum of days in prior months + current day
    uint32_t total = (year - 1970U) * 365U;
    static const uint8_t daysPerMonth[12] = {31,28,31,30,31,30,31,31,30,31,30,31};
    for (uint8_t i = 0; i < (month - 1); i++)
    {
        total += daysPerMonth[i];
    }
    total += (day - 1); // day is 1-based
    return total;
}

// Helper to convert back into a year/month/day (ignoring leap years)
static void daysToDate(uint32_t totalDays, systemTime* t)
{
    // Start at 1970
    uint16_t y = 1970;
    static const uint8_t daysPerMonth[12] = {31,28,31,30,31,30,31,31,30,31,30,31};
    while (totalDays >= 365)
    {
        totalDays -= 365;
        y++;
    }
    uint8_t m = 1;
    while (m <= 12 && totalDays >= daysPerMonth[m - 1])
    {
        totalDays -= daysPerMonth[m - 1];
        m++;
    }
    t->year  = y;
    t->month = m;
    t->day   = (uint8_t) (totalDays + 1);
}

// Add date parsing and increment logic
static void parseCompileDate(systemTime* time) {
    // __DATE__ format is "Mmm dd yyyy"
    const char* dateStr = __DATE__;
    uint8_t day;
    if (dateStr[4] == ' ') {
        // Single-digit day
        day = (uint8_t)(dateStr[5] - '0');
    } else {
        // Two-digit day
        day = (uint8_t)(((dateStr[4] - '0') * 10) + (dateStr[5] - '0'));
    }
    uint16_t year = ((dateStr[7] - '0') * 1000) + ((dateStr[8] - '0') * 100) + ((dateStr[9] - '0') * 10) + (dateStr[10] - '0');
    
    // Convert month string to number
    uint8_t month = 0;
    if (strncmp(dateStr, "Jan", 3) == 0) month = 1;
    else if (strncmp(dateStr, "Feb", 3) == 0) month = 2;
    else if (strncmp(dateStr, "Mar", 3) == 0) month = 3;
    else if (strncmp(dateStr, "Apr", 3) == 0) month = 4;
    else if (strncmp(dateStr, "May", 3) == 0) month = 5;
    else if (strncmp(dateStr, "Jun", 3) == 0) month = 6;
    else if (strncmp(dateStr, "Jul", 3) == 0) month = 7;
    else if (strncmp(dateStr, "Aug", 3) == 0) month = 8;
    else if (strncmp(dateStr, "Sep", 3) == 0) month = 9;
    else if (strncmp(dateStr, "Oct", 3) == 0) month = 10;
    else if (strncmp(dateStr, "Nov", 3) == 0) month = 11;
    else if (strncmp(dateStr, "Dec", 3) == 0) month = 12;
    
    time->day = day;
    time->month = month;
    time->year = year;
    // Save base date in total days
    baseDateDays = dateToDays(time->year, time->month, time->day);
}

// Add helper functions for safe conversion
uint8_t safeHourConversion(uint32_t hours) {
    return (uint8_t)(hours % 24);
}

uint8_t safeMinSecConversion(uint32_t value) {
    return (uint8_t)(value % 60);
}

uint16_t safeMillisConversion(uint32_t ms) {
    return (uint16_t)(ms % 1000);
}

rawtime getRawTime(void) {
    // Get precise time from STM
    uint64_t currentTicks = IfxStm_get(&MODULE_STM0);
    uint32_t frequency = IfxStm_getFrequency(&MODULE_STM0);
    
    // Remove continuous overhead subtraction to ensure ms updates each call
    uint64_t adjustedTicks = currentTicks; // no subtraction of processingOverhead

    // Calculate total seconds and remainder
    uint64_t totalSeconds = adjustedTicks / frequency;
    //uint32_t remainderTicks = (uint32_t)(adjustedTicks % frequency);
    
    // Update the raw time structure
    g_rawtime.totalSeconds = (uint32_t)(totalSeconds & 0xFFFFFFFF);
    
    uint32_t timeInDay = g_rawtime.totalSeconds % DAY_IN_SECONDS;
    g_rawtime.hours   = (uint8_t)(timeInDay / HOURS_IN_SECONDS);
    g_rawtime.minutes = (uint8_t)((timeInDay % HOURS_IN_SECONDS) / MIN_IN_SECONDS);
    g_rawtime.seconds = (uint8_t)(timeInDay % MIN_IN_SECONDS);
    g_rawtime.days    = (uint32_t)(totalSeconds / DAY_IN_SECONDS);

    return g_rawtime;
}

static uint64_t getAdjustedTicks(void) {
    uint64_t currentTicks = IfxStm_get(&MODULE_STM0);
    if (processingOverhead > 0) {
        return currentTicks - processingOverhead;
    }
    return currentTicks;
}

// Function to update the date based on elapsed time
static void updateDate(systemTime* time, uint64_t totalSeconds)
{
    uint32_t offsetDays = (uint32_t)(totalSeconds / DAY_IN_SECONDS);
    uint32_t currentDays = baseDateDays + offsetDays;
    daysToDate(currentDays, time);
}

systemTime getTime(void) {
    if (!timeInitialized) {
        // Parse compile time and date once
        parseCompileDate(&g_time);    // sets baseDateDays
        const char* timeStr = __TIME__;  // Format: "HH:MM:SS"
        int hour = ((timeStr[0] - '0') * 10) + (timeStr[1] - '0');
        int min = ((timeStr[3] - '0') * 10) + (timeStr[4] - '0');
        int sec = ((timeStr[6] - '0') * 10) + (timeStr[7] - '0');
        
        // Convert to total seconds for base time
        baseSeconds = (hour * HOURS_IN_SECONDS) + (min * MIN_IN_SECONDS) + sec;
        timeInitialized = TRUE;
    }

    uint64_t adjustedTicks = getAdjustedTicks();
    uint32_t frequency = IfxStm_getFrequency(&MODULE_STM0);
    
    // Calculate precise time components
    uint64_t totalSeconds = (adjustedTicks / frequency);

    // Include baseSeconds in the total elapsed time
    totalSeconds += baseSeconds;

    // Update the date based on elapsed time
    updateDate(&g_time, totalSeconds);

    // Then fill in hours, minutes, and seconds for the same day
    uint32_t timeInDay = (uint32_t)(totalSeconds % DAY_IN_SECONDS);
    g_time.hours   = safeHourConversion(timeInDay / HOURS_IN_SECONDS);
    g_time.minutes = safeMinSecConversion((timeInDay % HOURS_IN_SECONDS) / MIN_IN_SECONDS);
    g_time.seconds = safeMinSecConversion(timeInDay % MIN_IN_SECONDS);
    
    return g_time;
}

// Remove setTestMode function
// void setTestMode(boolean mode, uint32_t speedMs) { ... }


//// until here demihu3